# Generated by Django 5.1.3 on 2024-11-18 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='apellido',
            field=models.CharField(default='roman', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='perfil',
            name='email',
            field=models.EmailField(default='roman@gmail.com', max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='perfil',
            name='nombre',
            field=models.CharField(default='vale', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='perfil',
            name='password',
            field=models.CharField(default='12345', max_length=128),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='perfil',
            name='rol',
            field=models.CharField(choices=[('administrador', 'Administrador'), ('vendedor', 'Vendedor'), ('usuario', 'Usuario')], max_length=20),
        ),
    ]
