# Generated by Django 5.1.3 on 2024-11-18 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_perfil_apellido_perfil_email_perfil_nombre_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfil',
            name='nombre',
        ),
        migrations.AlterField(
            model_name='perfil',
            name='rol',
            field=models.CharField(choices=[('administrador', 'Administrador'), ('vendedor', 'Vendedor')], max_length=20),
        ),
    ]
