# Generated by Django 5.1.3 on 2024-11-25 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_remove_perfil_nombre_alter_perfil_rol'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfil',
            name='email',
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='password',
        ),
        migrations.AddField(
            model_name='perfil',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='fotos_perfil'),
        ),
        migrations.AddField(
            model_name='perfil',
            name='nombre',
            field=models.CharField(default='sin nombre', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='perfil',
            name='rol',
            field=models.CharField(choices=[('administrador', 'Administrador'), ('vendedor', 'Vendedor')], default='usuario', max_length=20),
        ),
    ]
